require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.none-ls"
spec "user.whichkey"
spec "user.telescope"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.raygo"
spec "user.go_lsp_signature"
spec "user.breadcrumbs" -- Shows file name with the context at the top
spec "user.illuminate"
spec "user.ufo" -- folds
spec "user.autopair"
spec "user.extras.eyeliner" -- Highlight a character in word for f-jump
spec "user.neotest"
spec "user.gitsigns"
spec "user.neogit"
spec "user.indentline"
spec "user.toggleterm"
spec "user.fidget" -- Show lsp status at bottom right
spec "user.bfq" -- QuickFix list
spec "user.navbuddy"
spec "user.extras.harpoon"
spec "user.extras.tabby" -- tab manager
spec "user.extras.smoothie"
spec "user.extras.wakatime"
spec "user.extras.codeium"
require "user.lazy"
